development:
  adapter: postgresql
  encoding: unicode
  database: bazar_development
  pool: 5
  username: bazar
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bazar_test
  pool: 5
  username: bazar
  password:

  production:
    adapter: postgresql
    encoding: unicode
    database: bazar_test
    pool: 5
    username: bazar
    password: